# Generated by Django 5.1.7 on 2025-05-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_description',
            field=models.TextField(),
        ),
    ]
