# Generated by Django 5.1.7 on 2025-05-13 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('motocycleImage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_product', to='category.category')),
                ('motocycleImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_of_product', to='motocycleImage.motocycleimage')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
