# Generated by Django 5.1.7 on 2025-06-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='motocycleImage',
        ),
    ]
