# Generated by Django 5.1.7 on 2025-05-15 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocycleImage', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motocycleimage',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='motocycleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motorcycle_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='motocycleimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
