# Generated by Django 5.1.7 on 2025-05-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motocycleImage', '0003_remove_motocycleimage_imageurl_motocycleimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motocycleimage',
            name='moto',
        ),
    ]
