# Generated by Django 5.1.7 on 2025-05-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertb',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], max_length=50),
        ),
    ]
