# Generated by Django 5.1.7 on 2025-05-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usertb_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertb',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
