# Generated by Django 5.1.7 on 2025-03-19 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0002_alter_contract_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Contract', 'In Contract'), ('Returned', 'Returned')], default='Available', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='contract.contract')),
            ],
        ),
    ]
