# Generated by Django 5.1.7 on 2025-05-13 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
